DROP DATABASE IF EXIST kppong;

CREATE DATABASE kppong;

USE kppong;

CREATE TABLE `user` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	VARCHAR(15)	NOT NULL	COMMENT 'Unique Key',
	`gradeId`	INT	NULL	COMMENT '1. 골드
2. 실버
3. 브론즈',
	`userType`	INT	NOT NULL	DEFAULT 2	COMMENT '1.관리자 
2. 일반
3. 사업자',
	`name`	VARCHAR(15)	NOT NULL,
	`email`	VARCHAR(40)	NOT NULL,
	`passwd`	VARCHAR(40)	NOT NULL,
	`nickName`	VARCHAR(15)	NOT NULL,
	`phoneNum`	VARCHAR(15)	NOT NULL,
	`birthAt`	DATE	NOT NULL,
	`national`	VARCHAR(15)	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE(),
	`isExpelled`	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT 'N/Y',
	`businessId`	INT	NULL	DEFAULT NULL,
	`reportId`	INT	NULL	DEFAULT NULL
);

CREATE TABLE `userType` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`name`	VARCHAR(5)	NOT NULL	COMMENT '1. 관리자
2. 일반 (회원)
3. 사업자 (회원)'
);

CREATE TABLE `business` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`businessNum`	VARCHAR(15)	NOT NULL,
	`name`	VARCHAR(15)	NOT NULL,
	`certDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT 'N/Y',
	`certedAt`	TIMESTAMP	NULL	DEFAULT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `order` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL,
	`isPay`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`status`	INT	NOT NULL	COMMENT '진행, 확정, 취소',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `package` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL	COMMENT 'user 외래키',
	`cultureArea`	INT	NOT NULL,
	`name`	VARCHAR(15)	NOT NULL,
	`price`	INT	NOT NULL,
	`info`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE(),
	`startDate`	DATETIME	NOT NULL,
	`endDate`	DATETIME	NOT NULL,
	`deadlineDate`	DATETIME	NOT NULL
);

CREATE TABLE `cart` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `like` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE()
);

CREATE TABLE `sellerReview` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`orderId`	INT	NOT NULL,
	`content`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `grade` (
	`id`	INT	NOT NULL	COMMENT '1. 골드
2. 실버
3. 브론즈',
	`name`	VARCHAR(3)	NOT NULL
);

CREATE TABLE `board` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL	COMMENT '회원 외래키',
	`title`	VARCHAR(15)	NOT NULL,
	`content`	TEXT	NULL	COMMENT '500글자 이내',
	`tmpDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `comment` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`boardNo`	INT	NOT NULL,
	`userId`	INT	NOT NULL,
	`content`	TEXT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `caution` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`reason`	VARCHAR(200)	NOT NULL	COMMENT '200자 이내',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `report` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`reportingId`	INT	NOT NULL,
	`reported_user_id`	INT	NOT NULL,
	`reason`	VARCHAR(200)	NULL,
	`reportDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`reportResult`	TEXT	NULL,
	`resultedAt`	TIMESTAMP	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `favorite` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`userId`	INT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `packageReview` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`orderId`	INT	NOT NULL,
	`content`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `cultureArea` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`name`	VARCHAR(30)	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE(),
	`cultureCategory`	INT	NOT NULL,
	`area`	INT	NOT NULL
);

CREATE TABLE `cultureCategory` (
	`id`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`name`	VARCHAR(10)	NOT NULL	COMMENT '오락, 문화, 쇼핑 등',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT CURDATE(),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT CURDATE()
);

CREATE TABLE `areaCategory` (
	`no`	INT	NOT NULL	AUTO_INCREMENT unique key,
	`name`	VARCHAR(15)	NOT NULL
);

ALTER TABLE `user` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`id`
);

ALTER TABLE `userType` ADD CONSTRAINT `PK_USERTYPE` PRIMARY KEY (
	`id`
);

ALTER TABLE `business` ADD CONSTRAINT `PK_BUSINESS` PRIMARY KEY (
	`id`
);

ALTER TABLE `order` ADD CONSTRAINT `PK_ORDER` PRIMARY KEY (
	`id`
);

ALTER TABLE `package` ADD CONSTRAINT `PK_PACKAGE` PRIMARY KEY (
	`id`
);

ALTER TABLE `cart` ADD CONSTRAINT `PK_CART` PRIMARY KEY (
	`id`
);

ALTER TABLE `like` ADD CONSTRAINT `PK_LIKE` PRIMARY KEY (
	`id`
);

ALTER TABLE `sellerReview` ADD CONSTRAINT `PK_SELLERREVIEW` PRIMARY KEY (
	`id`
);

ALTER TABLE `grade` ADD CONSTRAINT `PK_GRADE` PRIMARY KEY (
	`id`
);

ALTER TABLE `board` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`id`
);

ALTER TABLE `comment` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`id`
);

ALTER TABLE `caution` ADD CONSTRAINT `PK_CAUTION` PRIMARY KEY (
	`id`
);

ALTER TABLE `report` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`id`
);

ALTER TABLE `favorite` ADD CONSTRAINT `PK_FAVORITE` PRIMARY KEY (
	`id`
);

ALTER TABLE `packageReview` ADD CONSTRAINT `PK_PACKAGEREVIEW` PRIMARY KEY (
	`id`
);

ALTER TABLE `cultureArea` ADD CONSTRAINT `PK_CULTUREAREA` PRIMARY KEY (
	`id`
);

ALTER TABLE `cultureCategory` ADD CONSTRAINT `PK_CULTURECATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `areaCategory` ADD CONSTRAINT `PK_AREACATEGORY` PRIMARY KEY (
	`no`
);

