DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	VARCHAR(15)	NOT NULL	COMMENT 'Unique Key',
	`gradeId`	INT	NULL	COMMENT '1. 골드
2. 실버
3. 브론즈',
	`userType`	INT	NOT NULL	DEFAULT 2	COMMENT '1.관리자 
2. 일반
3. 사업자',
	`name`	VARCHAR(15)	NOT NULL,
	`email`	VARCHAR(40)	NOT NULL,
	`passwd`	VARCHAR(40)	NOT NULL,
	`nickName`	VARCHAR(15)	NOT NULL,
	`phoneNum`	VARCHAR(15)	NOT NULL,
	`birthAt`	DATE	NOT NULL,
	`national`	VARCHAR(15)	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE()),
	`isExpelled`	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT 'N/Y',
	`businessId`	INT	NULL	DEFAULT NULL,
	`reportId`	INT	NULL	DEFAULT NULL
);

DROP TABLE IF EXISTS `userType`;

CREATE TABLE `userType` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`name`	VARCHAR(5)	NOT NULL	COMMENT '1. 관리자
2. 일반 (회원)
3. 사업자 (회원)',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `business`;

CREATE TABLE `business` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`businessNum`	VARCHAR(15)	NOT NULL,
	`name`	VARCHAR(15)	NOT NULL,
	`certDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT 'N/Y',
	`certedAt`	TIMESTAMP	NULL	DEFAULT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL,
	`status`	INT	NOT NULL	COMMENT '진행, 확정, 취소',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `package`;

CREATE TABLE `package` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL	COMMENT 'user 외래키',
	`cultureArea`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`name`	VARCHAR(15)	NOT NULL,
	`price`	INT	NOT NULL,
	`info`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE()),
	`startDate`	DATETIME	NOT NULL,
	`endDate`	DATETIME	NOT NULL,
	`deadlineDate`	DATETIME	NOT NULL
);

DROP TABLE IF EXISTS `cart`;

CREATE TABLE `cart` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `like`;

CREATE TABLE `like` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`packageId`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `sellerReview`;

CREATE TABLE `sellerReview` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`orderId`	INT	NOT NULL,
	`content`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `grade`;

CREATE TABLE `grade` (
	`id`	INT	NOT NULL	COMMENT '1. 골드
2. 실버
3. 브론즈',
	`name`	VARCHAR(3)	NOT NULL
);

DROP TABLE IF EXISTS `board`;

CREATE TABLE `board` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL	COMMENT '회원 외래키',
	`title`	VARCHAR(15)	NOT NULL,
	`content`	TEXT	NULL	COMMENT '500글자 이내',
	`tmpDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `comment`;

CREATE TABLE `comment` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`boardNo`	INT	NOT NULL,
	`userId`	INT	NOT NULL,
	`content`	TEXT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `caution`;

CREATE TABLE `caution` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`reason`	VARCHAR(200)	NOT NULL	COMMENT '200자 이내',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `report`;

CREATE TABLE `report` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`reportingId`	INT	NOT NULL,
	`reported_user_id`	INT	NOT NULL,
	`reason`	VARCHAR(200)	NULL,
	`reportDist`	VARCHAR(1)	NOT NULL	DEFAULT 'N',
	`reportResult`	TEXT	NULL,
	`resultedAt`	TIMESTAMP	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `favorite`;

CREATE TABLE `favorite` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`userId`	INT	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `productReview`;

CREATE TABLE `productReview` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`orderId`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`content`	TEXT	NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

kppongDROP TABLE IF EXISTS `cultureArea`;

CREATE TABLE `cultureArea` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`name`	VARCHAR(30)	NOT NULL,
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE()),
	`cultureCategory`	INT	NOT NULL,
	`area`	INT	NOT NULL
);

DROP TABLE IF EXISTS `cultureCategory`;

CREATE TABLE `cultureCategory` (
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`name`	VARCHAR(10)	NOT NULL	COMMENT '오락, 문화, 쇼핑 등',
	`createdAt`	TIMESTAMP	NOT NULL	DEFAULT (CURDATE()),
	`updatedAt`	TIMESTAMP	NULL	DEFAULT (CURDATE())
);

DROP TABLE IF EXISTS `areaCkppongategory`;

CREATE TABLE `areaCategory` (
	`no`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT()',
	`name`	VARCHAR(15)	NOT NULL
);

